config/routes.rb
Rails.application.routes.draw do
  resources :host_redirects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/host_redirect.rb
class HostRedirect < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/host_redirects_controller.rb
class HostRedirectsController < ApplicationController
  before_action :set_host_redirect, only: [:show, :edit, :update, :destroy]

  # GET /host_redirects
  # GET /host_redirects.json
  def index
    @host_redirects = HostRedirect.all
  end

  # GET /host_redirects/1
  # GET /host_redirects/1.json
  def show
  end

  # GET /host_redirects/new
  def new
    @host_redirect = HostRedirect.new
  end

  # GET /host_redirects/1/edit
  def edit
  end

  # POST /host_redirects
  # POST /host_redirects.json
  def create
    @host_redirect = HostRedirect.new(host_redirect_params)

    respond_to do |format|
      if @host_redirect.save
        format.html { redirect_to @host_redirect, notice: 'Host redirect was successfully created.' }
        format.json { render :show, status: :created, location: @host_redirect }
      else
        format.html { render :new }
        format.json { render json: @host_redirect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /host_redirects/1
  # PATCH/PUT /host_redirects/1.json
  def update
    respond_to do |format|
      if @host_redirect.update(host_redirect_params)
        format.html { redirect_to @host_redirect, notice: 'Host redirect was successfully updated.' }
        format.json { render :show, status: :ok, location: @host_redirect }
      else
        format.html { render :edit }
        format.json { render json: @host_redirect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /host_redirects/1
  # DELETE /host_redirects/1.json
  def destroy
    @host_redirect.destroy
    respond_to do |format|
      format.html { redirect_to host_redirects_url, notice: 'Host redirect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host_redirect
      @host_redirect = HostRedirect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_redirect_params
      params.require(:host_redirect).permit(:orig, :dest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/host_redirects_helper.rb
module HostRedirectsHelper
end

app/views/host_redirects/_form.html.erb
<%= form_for(host_redirect) do |f| %>
  <% if host_redirect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(host_redirect.errors.count, "error") %> prohibited this host_redirect from being saved:</h2>

      <ul>
      <% host_redirect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :orig %>
    <%= f.text_field :orig %>
  </div>

  <div class="field">
    <%= f.label :dest %>
    <%= f.text_field :dest %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/host_redirects/edit.html.erb
<h1>Editing Host Redirect</h1>

<%= render 'form', host_redirect: @host_redirect %>

<%= link_to 'Show', @host_redirect %> |
<%= link_to 'Back', host_redirects_path %>

app/views/host_redirects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Host Redirects</h1>

<table>
  <thead>
    <tr>
      <th>Orig</th>
      <th>Dest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @host_redirects.each do |host_redirect| %>
      <tr>
        <td><%= host_redirect.orig %></td>
        <td><%= host_redirect.dest %></td>
        <td><%= link_to 'Show', host_redirect %></td>
        <td><%= link_to 'Edit', edit_host_redirect_path(host_redirect) %></td>
        <td><%= link_to 'Destroy', host_redirect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host Redirect', new_host_redirect_path %>

app/views/host_redirects/new.html.erb
<h1>New Host Redirect</h1>

<%= render 'form', host_redirect: @host_redirect %>

<%= link_to 'Back', host_redirects_path %>

app/views/host_redirects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orig:</strong>
  <%= @host_redirect.orig %>
</p>

<p>
  <strong>Dest:</strong>
  <%= @host_redirect.dest %>
</p>

<%= link_to 'Edit', edit_host_redirect_path(@host_redirect) %> |
<%= link_to 'Back', host_redirects_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenrestryRedirects</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>